name: Sync with Upstream

on:
  schedule:
    # Runs every day at midnight (UTC)
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: main
          fetch-depth: 0

      # Configure Git identity
      - name: Configure Git Identity
        run: |
          git config --global user.email "actions.kipjr.mc-distant-horizons@github.com"
          git config --global user.name "GitHub Actions Bot"

      # Add the upstream remote
      - name: Add Upstream Remote
        run: git remote add gitlab_upstream https://gitlab.com/distant-horizons-team/distant-horizons.git

      # Fetch and merge upstream changes
      - name: Fetch and Merge Upstream
        run: |
          git fetch gitlab_upstream
          git checkout main
          git merge gitlab_upstream/main

      # Push changes to your fork
      - name: Push Changes to Fork
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin main
###
### PR
###
      # Checkout the target branch (kipjr-main)
      - name: Checkout Target Branch
        run: |
          git fetch origin
          git checkout Kipjr-main

      # Merge `main` into `OTHERBRANCH`
      - name: Merge Main into Kipjr-main
        run: git merge main

      # Push merged changes to OTHERBRANCH
      - name: Push to Target Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin Kipjr-main

      # Create a Pull Request
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth setup-git
          gh pr create --base kipjr-main --head main --title "Sync with Upstream" --body "This PR syncs changes from 'main' to 'Kipjr-main'."
