name: Sync with Upstream

on:
  schedule:
    # Runs every day at midnight (UTC)
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          ref: main

      # Add the upstream remote
      - name: Add Upstream Remote
        run: git remote add upstream https://gitlab.com/distant-horizons-team/distant-horizons.git

      # Fetch and merge upstream changes
      - name: Fetch and Merge Upstream
        run: |
          git fetch upstream
          git checkout main
          git merge upstream/main

      # Push changes to your fork
      - name: Push Changes to Fork
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin main
